version: '3.8'

services:
  web:
    build: ./web
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - "5173:5173"
    depends_on:
      - api
      - db
      - stats

  stats:
    build: ./stats
    volumes:
      - ./stats:/app
    working_dir: /app
    ports:
      - "5000:5500"
    depends_on:
      - api
      - db

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - "5000:5000"
    working_dir: /app
    env_file:
      - ./.env.dev
    depends_on:
      - db
  
  db:
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=banquito
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
