version: '3.8'

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    ports:
      - "5001:5000"
    env_file:
      - ./api/.env
    depends_on:
      - db
    
  stats:
    build: ./stats
    volumes:
      - ./stats:/app
    working_dir: /app
    ports:
      - "5000:5000"
    env_file:
      - ./stats/.env
    links:
      - api

  web:
    build: ./web
    volumes:
      - ./web:/app
      - node_modules:/app/node_modules
    working_dir: /app
    ports:
      - "5173:5173"
    env_file:
      - ./web/.env
    
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=Paqueteria
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  node_modules: