version: '3.8'

services:
  api:
    build: ./api
    volumes:
      - ./api:/app
    working_dir: /app
    env_file:
      - .env.dev
    depends_on:
      - db
    
  stats:
    build: ./stats
    volumes:
      - ./stats:/app
    working_dir: /app
    ports:
      - "5000:5000"
    links:
      - api
    
  db:
    image: postgres:16.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=Paqueteria
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: